import React, { useState } from "react";
import Head from "next/head";

// Styles
import styles from "../../styles/Home.module.css";
import Logos from "../../components/Logos/Logos";
import WebDesigns from "../../components/WebDesigns/WebDesigns";

const Index = () => {
    const [view, setView] = useState(0);

    return (
        <div className={`${styles.container} bg-bgColor`}>
            <Head>
                <title>Javano Collins | Design Work</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <header className="px-0 md:px-20 pt-20">
                <h1 className="text-5xl md:text-7xl mb-3 text-orange-500 text-center">
                    Design Work
                </h1>
                <p className="text-center text-white">Have a look at my designs.</p>
            </header>
            <main className="flex flex-col px-0 md:px-16 pt-20">
                <div className="flex justify-center items-center gap-x-3 mr-20 text-white">
                    <p
                        className={`text-4xl mb-8 cursor-pointer ${
                            view === 0 ? "font-bold" : "opacity-50"
                        }`}
                        onClick={() => setView(0)}
                    >
                        Web Designs
                    </p>
                    <p
                        className={`text-4xl mb-8 cursor-pointer ${
                            view === 1 ? "font-bold" : "opacity-50"
                        }`}
                        onClick={() => setView(1)}
                    >
                        Logos
                    </p>
                </div>
                {view === 0 && (
                    <div className="flex justify-center  py-20">
                        <WebDesigns />
                    </div>
                )}
                {view === 1 && (
                    <div className="flex justify-center py-20">
                        <Logos />
                    </div>
                )}
            </main>
        </div>
    );
};

export default Index;
