import React, { useState } from "react";
import Head from "next/head";

// Styles
import styles from "../../styles/Home.module.css";
import Logos from "../../components/Logos/Logos";
import WebDesigns from "../../components/WebDesigns/WebDesigns";

const Index = () => {
    const [view, setView] = useState(0);

    return (
        <div className={styles.container}>
            <Head>
                <title>Javano Collins | Design Work</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="px-20 mt-20">
                <h1 className="text-7xl mb-3 text-orange-500 text-center">
                    Design Work
                </h1>
                <p className="text-center">Have a look at my designs.</p>
            </header>
            <main className="flex flex-col px-20 py-20 w-full">
                <div className="flex justify-center items-center w-full gap-x-3 mr-20">
                    <p
                        className={`text-4xl mb-8 cursor-pointer ${
                            view === 0 ? "font-bold" : "opacity-50"
                        }`}
                        onClick={() => setView(0)}
                    >
                        Logos
                    </p>
                    <p
                        className={`text-4xl mb-8 cursor-pointer ${
                            view === 1 ? "font-bold" : "opacity-50"
                        }`}
                        onClick={() => setView(1)}
                    >
                        Web Designs
                    </p>
                </div>
                <div className="flex justify-center">
                    {view === 0 && <Logos />}
                </div>
                {view === 1 && <WebDesigns />}
            </main>
        </div>
    );
};

export default Index;
