import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavBar from "../components/NavBar";
import styles from "../styles/Home.module.css";
import Typewriter from "typewriter-effect";
import Button from "../components/Button/Button";
import Tool from "../components/Tool/Tool";
import { toolIcons } from "../utils/utils";
import { fab, faLaravel } from "@fortawesome/free-brands-svg-icons";
import {
    faCheckSquare,
    faCoffee,
    faDatabase,
} from "@fortawesome/free-solid-svg-icons";
import { library } from "@fortawesome/fontawesome-svg-core";
import About from "../components/About/About";
library.add(fab, faDatabase);

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Javano Collins</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="HomePage-header flex flex-col px-10 items-start justify-center container mx-auto">
                <div className="flex text-7xl font-medium mb-1 flex-wrap">
                    <h1 className="">I am Javano Collins.&nbsp;</h1>
                    <Typewriter
                        className="Typewriter"
                        onInit={(typewriter) => {
                            typewriter
                                .typeString(
                                    '<span style="color: #F44006;">Software Engineer.</span>'
                                )
                                .pauseFor(2500)
                                .deleteAll()
                                .typeString(
                                    '<span style="color: #F44006;">UI/UX Designer.</span>'
                                )
                                .pauseFor(2500)
                                .deleteAll()
                                .start();
                        }}
                        options={{
                            autoStart: true,
                            loop: true,
                        }}
                    />
                </div>

                <p className="mb-3">I specialize in Web Development.</p>

                <Button
                    link="/dev-work"
                    title="View My Work"
                    activeColor="#47E5BC"
                ></Button>
            </header>
            <main className={styles.main}>
                <div className="Tools px-12 bg-black h-56 flex items-center justify-around">
                    {toolIcons.map((icon, idx) => {
                        return (
                            <Tool
                                key={idx}
                                icon={icon.icon}
                                title={icon.title}
                            />
                        );
                    })}
                </div>

                <div className="About bg-gradient-to-r from-orange-500 to-orange-700">
                    <About />
                </div>
            </main>

            {/* <footer className={styles.footer}></footer> */}
        </div>
    );
}
