import React, { useState } from "react";
import Head from "next/head";

// Styles
import styles from "../../styles/Home.module.css";


const Index = () => {
    const { view, setView } = useState(0);
    return (
        <div className={styles.container}>
            <Head>
                <title>Javano Collins | Dev Work</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <header className="px-20 mt-20 mb-16">
                <h1 className="text-7xl mb-3 text-orange-500">Dev Work</h1>
                <p>Have a look at my development work.</p>
            </header>
            <main className="px-20">

            </main>
        </div>
    );
};

export default Index